
---
apiVersion: v1 
kind: Pod 
metadata:
   name: back-end
   lables:
       app: my-back-end
spec:
   containers:
   - name: back-end
     image: deepakumre/backend-blog-web
     ports:
     - containerPort: 3000
...
---
apiVersion: v1
kind: Service
metadata:
   name: my-service2
spec:
  type: NodePort
  selector:
     app: my-back-end
  ports: 
  - port: 3000
    targetPort: 3000
    nodePort: 30012
...
